routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'BandController@index');

Route::resource('albums', 'AlbumController');
Route::resource('bands', 'BandController'); 

app/Band.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Band extends Model
{
  public function albums()
  {
    return $this->hasMany('App\Album');
  }
}

app/Http/Controllers/BandController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Band as Band;
use Session;

class BandController extends Controller
{
  public function index(Request $request)
  {
  	$bands = Band::all();
  	// apply sorting, if necessary
  	if($request->input('sort') !== '')
  	{
  	  $sort = $request->input('sort');
  	  $sortdirection = $request->sortdirection;
  	  $this->sort($bands, $sort, $sortdirection);
  	  // this has to come afterward so that toggling works
  	  $sortdirection = $request->sortdirection === 'asc' ? 'desc' : 'asc'; 
  	}

  	return view('bands.index', ['bands' => $bands, 'sort' => $sort, 'sortdirection' => $sortdirection]);
  }

  public function create()
  {
  	return view('bands.create');
  }

  public function store(Request $request)
  {
  	// validate the data
  	$this->validate($request, [
  	  'name' 	   	=> 'required|unique:bands, name|max:255|string',
  	  'start_date' 	=> 'nullable|string',
  	  'website'	   	=> 'nullable|url',
  	  'still_active'=> 'boolean'
  	]);

    // extract and store data
    $band = new Band();
    $band->name = $request->name;
    $band->start_date = $request->start_date;
    $band->website = $request->website;
    $band->still_active = (bool)$request->still_active;
    $band->save();

    // flash message
    Session::flash('success', "The band $band->name was successfully saved!");

    // return show route
    return redirect()->route('bands.show', ['band' => $band]);
  }

  public function show($id)
  {
  	$band = Band::find($id);
  	return view('bands.show', ['band' => $band]);
  }

  public function edit($id)
  {
  	$band = Band::find($id);
  	return view('bands.edit', ['band' => $band]);
  }

  public function update(Request $request, $id)
  {
  	// validate the data
  	$band = Band::find($id);
  	if($band->name === $request->name)
  	{
  	  $this->validate($request, [
  	  	  'start_date' 	=> 'sometimes|string',
  	  	  'website'    	=> '',
  	  	  'still_active'=> 'sometimes|boolean'
  	  ]);
  	} else {
  	  $this->validate($request, [
  	  	'name' 			=> 'required|max:255|alpha_dash',
  	  	'start_date'	=> 'nullable|string',
  	  	'website' 		=> 'nullable|url',
  	  	'still_active'  => 'boolean'
  	  ]);
  	}

  	// extract and store data
  	$band = Band::find($id);
  	$band->name = $request->name;
  	$band->start_date = $request->start_date;
  	$band->website = $request->website;
  	$band->still_active = $request->still_active;
  	$band->save();

  	// flash message
  	Session::flash('success', "The band $band->name was successfully saved!");

  	// return show route
  	return redirect()->route('bands.show', ['band' => $band]);
  }

  public function destroy($id)
  {
  	$band = Band::find($id);
  	$albums = $band->albums;
  	if($albums->count() !== 0)
  	{
  	  foreach($albums as $album)
  	  {
  	  	$album->delete();
  	  }
  	}
  	$band->delete();
  	Session::flash('success', "$band->name and their albums were successfully deleted.");
  	return redirect()->route('bands.index');
  }
}

resources/views/bands/create.blade.php
@extends('layouts.public')

@section('headerscripts')

@stop

@section('title', 'Add New Band')

@section('content')
  {{-- {{ dd(session()->getOldInput()) }} --}}
  {{-- {!! $old = session()->getOldInput() !!} --}}
  {{-- {{ dd($old) }} --}}
<div class="row title-line">
  <div class="col-sm-8 col-md-6 col-md-offset-2">
    <h1>Add New Band</h1>
  </div>
</div>
<div class="row data">
  <div class="col-md-8 col-md-offset-2">
    <form class="form" action="/bands" method="post">
      {{ csrf_field() }}
      <div class="form-group">
        <label for="name">Band Name:</label>
        <input class="form-control" type="text" name="name" value="{{ old('name', '') }}">
      </div>
      <div class="form-group">
        <label for="start_date">Start Date:</label>
        <input class="form-control" type="text" name="start_date" value="{{ old('start_date', '') }}">
      </div>
      <div class="form-group">
        <label for="website">Website:</label>
        <input class="form-control" type="text" name="website" value="{{ old('website', '') }}">
      </div>
      <div class="form-group">
        <label for="still_active">Still Active:</label>
        <select class="form-control" name="still_active">
          <option value="0" {{ old('still_active', '') == false ? 'selected' : '' }}>False</option>
          <option value="1" {{ old('still_active', '') == false ? '' : 'selected' }}>True</option>
        </select>
      </div>

      <a class="btn btn-danger" href="{{ URL::previous() }}">Back</a>
      <button class="btn btn-success" type="submit" name="button">Save</button>
    </form>
  </div>
</div>

@stop

resources/views/bands/edit.blade.php
@extends('layouts.public')

@section('headerscripts')

@stop

@section('title', 'Edit Band')

@section('content')
<div class="row title-line">
  <div class="col-sm-8 col-md-6 col-md-offset-2">
    <h1>Edit {{ $band->name }}</h1>
  </div>
</div>
<div class="row data">
  <div class="col-md-8 col-md-offset-2">
    <form class="form" action="/bands/{{ $band->id }}" method="post">
      {{ method_field('PUT') }}
      {{ csrf_field() }}
      <div class="form-group">
        <label for="name">Band Name:</label>
        <input class="form-control" type="text" name="name" value="{{ $band->name }}">
      </div>
      <div class="form-group">
        <label for="start_date">Start Date:</label>
        <input class="form-control" type="text" name="start_date" value="{{ $band->start_date }}">
      </div>
      <div class="form-group">
        <label for="website">Website:</label>
        <input class="form-control" type="text" name="website" value="{{ $band->website }}">
      </div>
      <div class="form-group">
        <label for="still_active">Still Active:</label>
        <select class="form-control" name="still_active">
          <option value="0" {{ $band->still_active ? '' : 'selected' }}>False</option>
          <option value="1" {{ $band->name ? 'selected' : '' }}>True</option>
        </select>
      </div>

      <a class="btn btn-danger" href="{{ URL::previous() }}">Back</a>
      <button class="btn btn-success" type="submit" name="button">Save</button>
    </form>
  </div>
</div>

@stop

resources/views/bands/index.blade.php
@extends('layouts.public')

@section('title', 'Bands')

@section('content')
<div class="row title-line">
  <div class="col-sm-8 col-md-6 col-md-offset-2">
    <h1>All Bands</h1>
  </div>
  <div class="col-sm-2 col-sm-offset-1 col-md-2 col-md-offset-0">
    <a class="btn btn-success btn-headline" href="/bands/create">Add New Band</a>
  </div>
</div>
<div class="row data">
  <div class="col-md-8 col-md-offset-2 table-responsive">
    <table class='table'>
      <thead>
        <tr>
          <th><a href="{{ route('bands.index', ['sort' => 'name', 'sortdirection' => 'name' === $sort ? $sortdirection : 'asc']) }}">Name</a></th>
          <th><a href="{{ route('bands.index', ['sort' => 'start_date', 'sortdirection' => 'start_date' === $sort ? $sortdirection : 'asc']) }}">Start Date</a></th>
          <th><a href="{{ route('bands.index', ['sort' => 'website', 'sortdirection' => 'website' === $sort ? $sortdirection : 'asc']) }}">Website</a></th>
          <th><a href="{{ route('bands.index', ['sort' => 'still_active', 'sortdirection' => 'still_active' === $sort ? $sortdirection : 'asc']) }}">Still Active</a></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        @foreach($bands as $band)
          <tr>
            <td>
              <a href="/bands/{{ $band->id }}">{{ $band->name }}</a></td>
            <td>{{ $band->start_date }}</td>
            <td>
              <a target="_blank" href="{{ $band->website }}">{{ $band->website }}</a>
            </td>
            <td>{{ $band->still_active ? 'Yes' : 'No' }}</td>
            <td><a class="btn btn-info" href="/albums?band_id={{ $band->id }}">View Albums</a></td>
            <td><a class="btn btn-warning" href="/bands/{{ $band->id }}/edit">Edit</a></td>
            <td>
              <form class="" action="{{ route('bands.destroy', ['id' => $band->id]) }}" method="post">
                {{ method_field('DELETE') }}
                {{ csrf_field() }}
                <button class="btn btn-danger" type="submit" name="button">Delete</button>
              </form>
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>
@stop

resources/views/bands/show.blade.php
@extends('layouts.public')

@section('title', 'View ' . htmlspecialchars($band->name))

@section('content')

<div class="row title-line">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>{{ $band->name }}</h1>
  </div>
</div>
<div class="row data">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="row">
      <div class="col-xs-12">
        <dl class="dl-horizontal well">
          <dt>Start Date:</dt>
          <dd>{{ $band->start_date }}</dd>
          <dt>Website:</dt>
          <dd>
            <a target="_blank" href="{{ $band->website }}">{{ $band->website }}</a>
          </dd>
          <dt>Still Active:</dt>
          <dd>{{ $band->still_active ? 'True' : 'False' }}</dd>
          <dt>Albums:</dt>
          <dd>
            @foreach($band->albums as $album)
              <p><a href="/albums/{{ $album->id }}">{{ $album->name }}</a></p>
            @endforeach
          </dd>
        </dl>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-3">
        <a class="btn btn-info" href="{{ URL::previous() }}">Back</a>
      </div>
      <div class="col-sm-3 col-sm-offset-1">
        <a class="btn btn-warning" href="/bands/{{ $band->id }}/edit">Edit</a>
      </div>
      <div class="col-sm-3 col-sm-offset-1">
        <form class="" action="{{ route('bands.destroy', ['id' => $band->id]) }}" method="post">
          {{ method_field('DELETE') }}
          {{ csrf_field() }}
          <button class="btn btn-danger" type="submit" name="button">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>

@stop