routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'BandController@index');

Route::resource('albums', 'AlbumController');
Route::resource('bands', 'BandController'); 

app/Album.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Album extends Model
{
  public function band()
  {
  	return $this->belongsTo('App\Band', 'band_id');
  }
}

app/Http/Controllers/AlbumController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Album as Album;
use App\Band as Band;
use Session;

class AlbumController extends Controller
{
  public function index(Request $request)
  {
  	// if band_idis a parameter, get all albums by that
  	// band; otherwise return all.
  	if($request->band_id !== null)
  	{
  		$albums = Album::where('band_id', $request->band_id)->get();
  	} else 
  		{
  			$albums = Album::all();
  		}
  		// add band names as part of the album collection, so 
  		// we can sort by that column.
  		foreach($albums as $album)
  		{
  			$album->band_name = $album->band->name;
  		}
  		// apply sorting, if necessary
  		if($request->input('sort') !== '')
  		{
  			$sort = $request->input('sort');
  			$sortdirection = $request->sortdirection;
  			$this->sort($albums, $sort, $sortdirection);
  			// this has to come afterward so that toggling works.
  			$sortdirection = $request->sortdirection === 'asc' ? 'desc' : 'asc';
  		}

  		// get all bands, so we can populate the filter select. 
  		$bands = Band::all();

  		return view('albums.index', ['albums' => $albums, 'bands' => $bands, 'band_id' => $request->band_id, 'sort' => $sort, 'sortdirection' => $sortdirection]);
  }

  public function create(Request $request)
  {
  	$band_id = $request->band_id; // this is null if no band_id present.
  	$bands = Band::all();

  	return view('albums.create', ['band_id' => $band_id, 'bands' => $bands]);
  }

  public function store(Request $request)
  {
  	// validate the data
  	$this->validate($request, [
  	  'band_id' 		=> 'required|exists:bands,id|integer',
  	  'name'			=> 'required|max:255|string',
  	  'recorded_date'	=> 'nullable|string',
  	  'release_date'	=> 'nullable|string',
  	  'number_of_tracks'=> 'nullable|integer',
  	  'label'			=> 'nullable|max:255',
  	  'producer'		=> 'nullable|max:255',
  	  'genre'			=> 'nullable|max:255'
  	]);

  	// extract and store data
  	$album = new Album();
  	$album->band_id = $request->band_id;
  	$album->name = $request->name;
  	$album->recorded_date = $request->recorded_date;
  	$album->release_date = $request->release_date;
  	$album->number_of_tracks = $request->number_of_tracks;
  	$album->label = $request->label;
  	$album->producer = $request->producer;
  	$album->genre = $request->genre;
  	$album->save();

  	// flash message
  	Session::flash('success', "The album $album->name was successfully saved !");

  	// return show route
  	return redirect()->route('albums.show', ['id' => $album->id]);
  }

  public function show($id)
  {
  	$album = Album::find($id);
  	return view('albums.show', ['album' => $album]);
  }

  public function edit($id)
  {
  	$album = Album::find($id);
  	$bands = Band::all();
  	return view('albums.edit', ['album' => $album, 'bands' => $bands]);
  }

  public function update(Request $request, $id)
  {
  	// validate the data
  	$album = Album::find($id);
  	if($album->name === $request->name) 
  	{
  		$this->validate($request, [
  		   'band_id' 		 => 'required|exists:bands,id|integer',
  		   'recorded_date'   => 'nullable|string',
  		   'release_date'	 => 'nullable|integer',
  		   'number_of_tracks'=> 'nullable|integer',
  		   'label'			 => 'nullable|max:255',
  		   'producer'		 => 'nullable|max:255',
  		   'genre'			 => 'nullable|string'
  		]);
  	} else 
  		{
  			$this->validate($request, [
			 'band_id' 				=> 'required|exists:bands,id|integer',
			 'name'	  				=> 'required|max:255|string',
			 'recorded_date'	    => 'nullable|string',
			 'release_date'  		=> 'nullable|string',
			 'number_of_tracks'		=> 'nullable|integer',
			 'label'				=> 'nullable|max:255',
			 'producer'				=> 'nullable|max:255',
			 'genre'				=> 'nullable|string',
  			]);
  		}

  		// extract and store data
  		$album = Album::find($id);
  		$album->band_id = $request->band_id;
  		$album->name = $request->name;
  		$album->recorded_date = $request->recorded_date;
  		$album->release_date = $request->release_date;
  		$album->number_of_tracks = $request->number_of_tracks;
  		$album->label = $request->label;
  		$album->producer = $request->producer;
  		$album->genre = $request->genre;
  		$album->save();

  		// flash message
  		Session::flash('success', "The album $album->name was successfully saved!");

  		// return show route
  		return redirect()->route('albums.show', ['album' => $album]);
  }

  public function destory($id)
  {
  	$album = Album::find($id);
  	$album->delete();
  	Session::flash('success', "$album->name was successfully deleted.");
  	return redirect()->route('albums.index');
  }
}

resources/views/albums/create.blade.php
@extends('layouts.public')

@section('headerscripts')

@stop

@section('title', 'Add New Album')

@section('content')
<div class="row title-line">
 <div class="col-sm-8 col-md-6 col-md-offset-2">
  <h1>add new album</h1>
 </div>
</div>
<div class="row data">
<div class="col-md-8 col-md-offset-2">
<form class="form" action="/albums/" method="post">
 {{ csrf_field() }}
 <div class="form-group">
  <label for="band_id">band</label>
  <select class="form-control" name="band_id">
  @foreach($bands as $band)
  <option value="{{ $band->id }}" {{ $band->id === (int)$band_id ? 'selected' : '' }}>{{ $band->name }}</option>
  @endforeach
  </select>
 </div>
 <div class="form-group">
  <label for="name">album name:</label>
  <input class="form-control" type="text" name="name" value="">
 </div>
 <div class="form-group">
  <label for="recorded_date">recorded date:</label>
  <input class="form-control" type="text" name="recorded_date" value="">
 </div>
 <div class="form-group">
  <label for="release_date">release date:</label>
  <input class="form-control" type="text" name="release_date" value="">
 </div>
 <div class="form-group">
  <label for="number_of_tracks">number of tracks:</label>
  <input class="form-control" type="integer" name="number_of_tracks" value="">
 </div>
 <div class="form-group">
  <label for="producer">producer:</label>
  <input class="form-control" type="text" name="producer" value="">
 </div>
 <div class="form-group">
  <label for="genre">genre:</label>
  <input class="form-control" type="text" name="genre" value="">
 </div>

 <a class="btn btn-danger" href="{{ URL::previous() }}">back</a>
 <button class="btn btn-success" type="submit" name="button">save</button>
</form>
</div>
</div>

@stop

resources/views/albums/edit.blade.php
@extends('layouts.public')

@section('headerscripts')

@stop

@section('title', 'Edit Album')

@section('content')
<div class="row title-line">
 <div class="col-sm-8 col-md-6 col-md-offset-2">
  <h1>Edit {{ $album->name }}</h1>
  <h2>by {{ $album->band->name }}</h2>
 </div>
</div>
<div class="row data">
 <div class="col-md-8 col-md-offset-2">
  <form class="form" action="/albums/{{ $album->id }}" method="post">
    {{ method_field('PUT') }}
    {{ csrf_field() }}
    <div class="form-group">
     <label for="band_id">Band</label>
     <select class="form-control" name="band_id">
       @foreach($bands as $band)
         <option value=" $band->id }}" {{ $band->id === (int)$album->band->id ? 'selected' : '' }}>{{ $band->name }}</option>
       @endforeach
     </select>
    </div>
    <div class="form-group">
      <label for="name">album name:</label>
      <input class="form-control" type="text" name="name" value="{{ $album->name }}">
    </div>
    <div class="form-group">
      <label for="recorded_date">recorded date:</label>
      <input class="form-control" type="text" name="release_date" value="{{ $album->release_date }}">
    </div>
    <div class="form-group">
      <label for="number_of_tracks">number of tracks:</label>
      <input class="form-control" type="integer" name="number_of_tracks" value="{{ $album->number_of_tracks }}">
    </div>
    <div class="form-group">
      <label for="label">label:</label>
      <input class="form-control" type="text" name="label" value="{{ $album->label }}">
    </div>
    <div class="form-group">
      <label for="producer">producer:</label>
      <input class="form-control" type="text" name="producer" value="{{ $album->producer }}">
    </div>
    <div class="form-group">
      <label for="genre">genre:</label>
      <input class="form-control" type="text" name="genre" value="{{ $album->genre }}">
    </div>

    <a class="btn btn-danger" href="{{ URL::previous() }}">back</a>
    <button class="btn btn-success" type="submit" name="button">save</button>
   </form>
  </div>
 </div>

 @stop

resources/views/albums/index.blade.php
@extends('layouts.public')

@section('title', 'Albums')

@section('content')
<div class="row title-line">
  <div class="col-sm-8 col-md-6 col-md-offset-2">
    <h1>albums</h1>
  </div>
  <div class="col-sm-2 col-sm-offset-1 col-md-2 col-md-offset-0">
    <a class="btn btn-success btn-headline" href="/albums/create{{ $band_id !== null ? "?band_id=$band_id" : '' }}">add new album</a>
  </div>
</div>
<div class="row data">
  <div class="col-md-8 col-md-offset-2 table-responsive">
    <form id="bandselectform" class="" action="{{ route('albums.index') }}" method="get">
      {{ csrf_field() }}
      <div class="form-group">
        <label for="bandselect">filter by band</label>
        <select class="form-control" name="band_id" onchange="document.querySelector('#bandselectform').submit();">
          <option value="">(View All)</option>
          @foreach($bands as $band)
            <option value="{{ $band->id }}" {{ $band->id === (int)$band_id ? 'selected' : '' }}>{{ $band->name }}</option>
          @endforeach
        </select>
      </div>
    </form>
    <table class='table'>
      <thead>
        <tr>
          <th><a href="{{ route('albums.index', ['sort' => 'band_name', 'sortdirection' => 'band_name' === $sort ? $sortdirection : 'asc']) }}">band name</a></th>
          <th><a href="{{ route('albums.index', ['sort' => 'name', 'sortdirection' => 'name' === $sort ? $sortdirection : 'asc']) }}">album name</a></th>
          <th><a href="{{ route('albums.index', ['sort' => 'recorded_date', 'sortdirection' => 'recorded_date' === $sort ? $sortdirection : 'asc']) }}">recorded date</a></th>
          <th><a href="{{ route('albums.index', ['sort' => 'release_date', 'sortdirection' => 'release_date' === $sort ? $sortdirection : 'asc']) }}">release date</a></th>
          <th><a href="{{ route('albums.index', ['sort' => 'number_of_tracks', 'sortdirection' => 'number_of_tracks' === $sort ? $sortdirection : 'asc']) }}">number of tracks</a></th>
          <th><a href="{{ route('albums.index', ['sort' => 'label', 'sortdirection' => 'label' === $sort ? $sortdirection : 'asc']) }}">label</a></th>
          <th><a href="{{ route('albums.index', ['sort' => 'producer', 'sortdirection' => 'producer' === $sort ? $sortdirection : 'asc']) }}">producer</a></th>
          <th><a href="{{ route('albums.index', ['sort' => 'genre', 'sortdirection' => 'genre' === $sort ? $sortdirection : 'asc']) }}">genre</a></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        @foreach($albums as $album)
            <tr>
              <td>
                <a href="/bands/{{ $album->band->id }}">{{ $album->band->name }}</a>
              </td>
              <td>
                <a href="/albums/{{ $album->id }}">{{ $album->name }}</a>
              </td>
              <td>{{ $album->recorded_date }}</td>
              <td>{{ $album->release_date }}</td>
              <td>{{ $album->number_of_tracks }}</td>
              <td>{{ $album->label }}</td>
              <td>{{ $album->producer }}</td>
              <td>{{ $album->genre }}</td>
              <td><a class="btn btn-warning" href="/albums/{{ $album->id }}/edit">edit</a></td>
              <td>
                <form class="" action="{{ route('albums.destroy', ['id' => $album->id]) }}" method="post">
                  {{ method_field('DELETE') }}
                  {{ csrf_field() }}
                  <button class="btn btn-danger" type="submit" name="button">delete</button>
                </form>
              </td>
            </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>
@stop

resources/views/albums/show.blade.php
@extends('layouts.public')

@section('title', htmlspecialchars($album->name) . ' by ' .htmlspecialchars($album->band->name))

@section('content')

<div class="row title-line">
 <div class="col-sm-8 col-sm-offset-2">
  <h1>{{ $album->name }}</h1>
  <h2>by <a href="/bands/{{ $album->band->id }}">{{ $album->band->name }}</a></h2>
</div>
</div>
<div class="row data">
 <div class="col-sm-8 col-sm-offset-2">
  <div class="row">
   <div class="col-sm-12">
    <dl class="dl-horizontal well">
     <dt>name:</dt>
     <dd>{{ $album->name }}</dd>
     <dt>recorded date:</dt>
     <dd>{{ $album->recorded_date }}</dd>
     <dt>release date:</dt>
     <dd>{{ $album->release_date }}</dd>
     <dt>number of tracks:</dt>
     <dd>{{ $album->number_of_tracks }}</dd>
     <dt>label:</dt>
     <dd>{{ $album->label }}</dd>
     <dt>genre:</dt>
     <dd>{{ $album->genre }}</dd>
    </dl>
   </div>
  </div>
  <div class="row">
   <div class="col-sm-3">
    <a class="btn btn-info" href="{{ URL::previous() }}">back</a>
   </div>
   <div class="col-sm-3 col-sm-offset-1">
    <a class="btn btn-warning" href="/albums/{{ $album->id }}/edit">edit</a>
   </div>
   <div class="col-sm-3 col-sm-offset-1">
    <form class="" action="{{ route('albums.destroy', ['id' => $album->id]) }}" method="post">
      {{ method_field('DELETE') }}
      {{ csrf_field() }}
      <button class="btn btn-danger" type="submit" name="button">delete</button>
    </form>
   </div>
   </div>
  </div>
  </div>
 </div>
 @stop